ports:
- port: 8000
- port: 3000

tasks:
  - name: frontend
    init: |
      cd frontend
      npm install
    command: |
      cd frontend
      npm run dev
    openMode: split-left
  - name: cms
    init: |
      cd cms
      pip install poetry
      poetry config virtualenvs.create true 
      poetry config virtualenvs.in-project true 
      poetry env use python 
      poetry install
    command: |
      cd cms
      poetry run python manage.py runserver
    openMode: split-left