ports:
- port: 8000
  onOpen: open-browser
- port: 3000
  onOpen: open-preview


tasks:
  - name: python version
    init: |
      pyenv install 3.10.2
      pyenv global 3.10.2
      gp sync-done python
  - name: frontend
    init: |
      cd frontend
      npm install
    command: |
      gp await-port 8000
      eval $(gp env -e API_URL=$(gp url 8000))
      cd frontend
      npm run dev
    openMode: tab-after
  - name: cms
    init: |
      cd cms
      gp sync-await python
      pip install poetry
      poetry config virtualenvs.create true 
      poetry config virtualenvs.in-project true 
      poetry install
    command: |
      cd cms
      poetry run python manage.py runserver
    openMode: split-left