ports:
- port: 8000
- port: 3000

tasks:
  - name: frontend dependencies
    init: |
      npm run dev
      npm install
      npm run configure-database
    command: |
      cd frontend
      npm run dev
    openMode: split-left