import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

type HeadingBlock = {
  type: "heading";
  value: string;
};

type HTMLBlock = {
  type: "paragraph" | "text";
  value: string;
};

type TwoColumnsBlock = {
  type: "two_columns";
  value: [HTMLBlock, HTMLBlock];
};

type ImageBlock = {
  type: "image";
  value: {
    file: string;
    width: number;
    height: number;
  };
};

type BlockType = TwoColumnsBlock | HeadingBlock | ImageBlock | HTMLBlock;

const Block = ({ block }: { block: BlockType }) => {
  switch (block.type) {
    case "heading":
      return <h1>{block.value}</h1>;
    case "text":
    case "paragraph":
      console.log(block.value);
      return <div dangerouslySetInnerHTML={{ __html: block.value }} />;
    case "two_columns":
      return (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            width: "100%",
          }}
        >
          {block.value.map((b) => (
            <Block block={b} />
          ))}
        </div>
      );
    case "image":
      return (
        <Image
          src={block.value.file}
          width={block.value.width}
          height={block.value.height}
        />
      );
  }

  console.log(block);

  throw new Error("Unknown block type");
};

type Props = {
  blocks: BlockType[];
};

const Home: NextPage<{ title: string; body: BlockType[] }> = ({
  title,
  body,
}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {body.map((block) => (
          <Block block={block} key={block.type} />
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export async function getStaticProps() {
  const res = await fetch("http://localhost:8000/api/v2/pages/home");
  const data = await res.json();

  return {
    props: {
      title: data.title,
      body: data.body,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every minute
    revalidate: 60,
  };
}

export default Home;
